name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete --exclude '.git' --exclude 'site' --exclude 'archive'"
        SOURCE: ""
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: "puppet/"
    
    - name: Kick Puppet
      uses: appleboy/ssh-action@master
      env:
        DB_ROOT: ${{ secrets.DB_CONNECT_ROOT }}
        CLIENT_ID: ${{ secrets.MONEY_CLIENT_ID }}
      with:
        envs: DB_ROOT
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: sudo 
          FACTER_db_root=${DB_ROOT} FACTER_client_id=${CLIENT_ID} 
          /opt/puppetlabs/bin/puppet apply /etc/puppetlabs/code/environments/production/manifests/site.pp; [[ "02" == *"${PIPESTATUS[0]}"* ]]

  
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
    - uses: technote-space/workflow-conclusion-action@v1
    - name: send alert message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_NOTIFY_TO }}
        token: ${{ secrets.TGBOT_TOKEN }}
        message: |
          Puppet ${{ env.WORKFLOW_CONCLUSION }} ${{ github.event_name }} event.
